name: build

on:
  workflow_dispatch:
  push:

jobs:
  ros-robot:
    uses: ./.github/workflows/debs-from-repos.yaml
    with:
      repos: ros-robot
  ros-desktop:
    if: success() || failure() # can get cancelled
    needs: ros-robot
    uses: ./.github/workflows/debs-from-repos.yaml
    with:
      repos: ros-desktop
      depends: ros-robot
  ros-desktop-full:
    if: success() || failure() # can get cancelled
    needs: ros-desktop
    uses: ./.github/workflows/debs-from-repos.yaml
    with:
      repos: ros-desktop-full
      depends: ros-desktop
  universe-0:
    if: success() || failure() # can get cancelled
    needs: ros-desktop-full
    uses: ./.github/workflows/debs-from-repos.yaml
    with:
      repos: universe-0
      depends: ros-desktop-full
  universe-1:
    if: success() || failure() # can get cancelled
    needs: universe-0
    uses: ./.github/workflows/debs-from-repos.yaml
    with:
      repos: universe-1
      depends: universe-0
  universe-2:
    if: success() || failure() # can get cancelled
    needs: universe-1
    uses: ./.github/workflows/debs-from-repos.yaml
    with:
      repos: universe-2
      depends: universe-1
  deploy:
    needs: universe-2
    if: success() || failure() # can get cancelled
    runs-on: ubuntu-22.04
    env:
      ROS_DISTRO: one
      DEB_DISTRO: jammy
    steps:
      - name: get apt packages from last job
        uses: actions/cache/restore@v3
        with:
          path: /home/runner/apt_repo
          key: apt-repo-${{ env.DEB_DISTRO }}-${{ env.ROS_DISTRO }}-universe-2-${{ github.sha }}
      - uses: k-okada/ros-deb-builder-action/deploy@rosotest
        if: always() # alternatively success()
        with:
          BRANCH: ${{ env.DEB_DISTRO }}-${{ env.ROS_DISTRO }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SQUASH_HISTORY: true
